### ISSUE TITLE
Underground buildings

### ISSUE THREAD

**Issue by HarmenK** [tudelft3d/bag3d#27]
I have found at least one issue regarding an underground building that has a 'positive' height. Maybe 'underground buildings' should have been filtered out of the BAG dataset before heights are calculated?

Example: Marktgarage, Delft : Willem Naghelstraat 1, 2612 XD Delft
![image](https://user-images.githubusercontent.com/35258842/54529471-4a239c00-4980-11e9-9c61-15d83946b989.png)

**Comment by balazsdukai** [comment]
@HarmenK I looked into this a bit. Do you know how to filter out such underground buildings?

**Comment by HarmenK** [comment]
Well, that depends on the BAG data you use.
That's the first dataset I should look into: has a building an attribute where it says what it is or maybe if it is above the surface or is it subsurface?
Otherwise, you can maybe determine it by a combination of a geographical and a statistical approach on buildings. For example, buildings crossing roads and having a lot of 'weird' or low height values (below 2 metres).
Something like this maybe? I haven't done anything like that, these are some ideas. Love to hear how you solve it.

**Comment by balazsdukai** [comment]
Okay, I was hoping that you have a solution :-) . Neither in the BAG, nor in the BGT are there attributes that identify underground buildings. In theory the `relatieveHoogteligging` attribute in BGT could help, but in practice this is often not filled out or incorrect. As far as I know, Kadaster doesn't have a method for filtering out underground buildings either in their 3D model.

Thus only the hard way remains. I need to think more about this, as it seems non-trivial to find all (most) of the cases. I leave the issue open, because I agree with you, underground buildings shouldn't get a positive height in the 3D BAG.

**Comment by HarmenK** [comment]
Ok, so I would suggest a topographical check, like buildings on top of each other or overlapping with roads, parks and so on. But therefore you should have some use cases to create a solution and to validate.

Maybe we can collect in this thread some examples or find them by a geographical query

**Comment by evetion** [comment]
Rijswijk train station is mostly underground and does intersect other buildings. Its id: `0603100000015741`.

![rijswijk_station](https://user-images.githubusercontent.com/8655030/65832968-8aae8b80-e2ba-11e9-80ab-2a68bd824ac3.png)

**Comment by balazsdukai** [comment]
Repo closes because it has been superseded.
