### ISSUE TITLE
The "identificatie": number from the 3DBAG dataset is different from the "identificatie": number of the BAG dataset from Pdok

### ISSUE THREAD

**Issue by sebmooreaz** [tudelft3d/bag3d#32]
Hello,

I saw that the "identificatie": number from the 3DBAG dataset is different from the "identificatie": number of the BAG dataset from Pdok. 

It seems like the 3DBAG "identificatie" number always adds a 0 at the start of the number, am I correct?

**Comment by balazsdukai** [comment]
That's correct. In this case pdok is incorrect, because apparently they cast the `identificatie` to integers, which removes the 0-padding.

Why have a 0-padded ID? Because the first 4 digits of the ID is the municipality code, which begins below 1000.

For the correct `identificatie` attribute please refer to the official BAG viewer: https://bagviewer.kadaster.nl

**Comment by sebmooreaz** [comment]
Thank you for your reply, and thank you for the precise information. I will talk to the pdok community about it because it is quiet disturbing that an id value changes from one dataset source to the other.

I would like to add that 3dbag and other Tudelft projects are really well thought and really interesting. Thank you for that.
